### ISSUE TITLE
Adicionar categorias

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [vlaskz/stem-awesome-list#3]
Seria interessante colocar uma lista de categorias pra ajudar a saber qual a correta pra cada tipo de canal

**Comment by vlaskz** [comment]
Ótima ideia. Na minha segunda PR eu adicionei um formato padrão para os PR. As categorias serão inicialmente as equivalentes à STEM. Depois podemos adicionar mais, conforme diversificação do conteúdo.

Para o momento:
Categorias:
 - Ciência
 - Tecnologia
 - Engenharia
 - Matemática
